### ISSUE TITLE
Story #19: Design and implement a comprehensive homepage

### ISSUE THREAD

**Issue by Bitstachio** [hvpham-yorku/catalyst#10]
### User Story

As an app user, I want a more comprehensive homepage that describes the app so that I can understand its purpose, features, and how it can help me manage medical records effectively.

#### Front-end

- [ ] Create a static template `homepage.html`.
- [ ] Add and style sections for:
  - App description.
  - Features highlights (use icons or illustrations if available).
  - Benefits for users.
  - Call-to-action buttons (e.g., "Get Started").
- [ ] Make the design responsive for desktop and mobile views.

#### Content

- [ ] Write clear, concise content for the app description, features, and benefits sections.
- [ ] Include relevant images or icons to enhance the visual appeal.

#### Back-end (if necessary)

- [ ] Ensure the homepage is properly linked to the existing application routes.
- [ ] Configure any dynamic content or APIs required for the homepage.

**Comment by kevnngyen** [comment]
Related tickets:
https://trello.com/c/OqhLNEow/21-story-19-frontend-development-amir-ali-mohaghegh-as-an-app-user-i-want-a-more-comprehensive-homepage-that-describes-the-app-so-t
