### ISSUE TITLE
Story #1: CRUD functionality for optometrist records (Administrator)

### ISSUE THREAD

**Issue by Bitstachio** [hvpham-yorku/catalyst#8]
### User Story

As an administrator, I want to create, view, update, and delete optometrist records so that I can manage and maintain an accurate list of registered optometrists.

#### Front-end
- [x] Create and style static template `optometrists.html` for listing optometrist records.
- [x] Create a dedicated static template `optometrist-details.html` for the detailed view of each record.
- [x] Integrate back-end functionalities into front-end using Thymeleaf.

#### Back-end
- [x] Create a controller for handling the routes and requests related to optometrist records.
- [x] Create a service interface and implementation for business logic.
- [x] Create appropriate repositories/DAOs for handling database interactions.

**Comment by kevnngyen** [comment]
Related tickets:

https://trello.com/c/c2nLhjWV/3-story-11-backend-development-barbod-habibi-as-an-administrator-i-want-to-create-view-update-and-delete-optometrist-records-so-th

https://trello.com/c/r1Fl3jfI/24-story-12-frontend-development-kevin-nguyen-as-an-administrator-i-want-to-create-view-update-and-delete-optometrist-records-so-th

https://trello.com/c/SMj2oeih/26-story-121-input-validation-frontend-development-kevin-nguyen-as-an-administrator-i-want-to-create-view-update-and-delete-optomet
