### ISSUE TITLE
Story #2: CRUD functionality for patient records (Administrator)

### ISSUE THREAD

**Issue by Bitstachio** [hvpham-yorku/catalyst#9]
### User Story

As an administrator, I want to create, view, update, and delete patients records so that I can manage and maintain an accurate list of registered patients.

#### Front-end
- [ ] Create and style static template `patients.html` for listing patient records.
- [ ] Create a dedicated static template `patient-details.html` for the detailed view of each record.
- [ ] Integrate back-end functionalities into front-end using Thymeleaf.

#### Back-end
- [ ] Create a controller for handling the routes and requests related to patient records.
- [ ] Create a service interface and implementation for business logic.
- [ ] Create appropriate repositories/DAOs for handling database interactions.

**Comment by kevnngyen** [comment]
Related Tickets:
- https://trello.com/c/4KJhgpDo/23-story-22-frontend-development-kevin-nguyen-as-an-administrator-i-want-to-create-view-update-and-delete-patient-records-so-that-i
- https://trello.com/c/FSteSdKB/4-story-21-backend-development-barbod-habibi-as-an-administrator-i-want-to-create-view-update-and-delete-patient-records-so-that-i
- https://trello.com/c/gLQ4iffg/27-story-121-input-validation-frontend-development-kevin-nguyen-as-an-administrator-i-want-to-create-view-update-and-delete-optomet
